steps:
  # Docker 이미지 빌드
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/aifaker-insta",
        "./AIFAKER/insta/insta",
      ]

  # Docker 이미지 푸시
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/aifaker-insta"]

  # Compute Engine 인스턴스에 배포
  - name: "gcr.io/google-cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud compute ssh web-server-20250321-035425 --zone=us-central1-a --command='sudo docker pull gcr.io/$PROJECT_ID/aifaker-insta && sudo docker stop aifaker-insta && sudo docker rm aifaker-insta && sudo docker run -d -p 5000:5000 --name aifaker-insta gcr.io/$PROJECT_ID/aifaker-insta'
